Spring boot hw 2
ShemsheyMaxim/online-banking pull request #2
Opened 2021-03-29 12:26 UTC by ShemsheyMaxim

2021-03-29 14:37 UTC, KseniiaMakarova requested changes

2021-03-29 14:37 UTC, KseniiaMakarova commented on src/main/java/com/springboot/onlinebanking/model/Currency.java
> +@Table(name = "cyrrencies")
```suggestion
@Table(name = "currencies")
```

2021-03-29 14:37 UTC, KseniiaMakarova commented on src/main/java/com/springboot/onlinebanking/model/Transaction.java
> +    @OneToOne
why ManyToOne?

2021-03-29 14:37 UTC, KseniiaMakarova commented on src/main/java/com/springboot/onlinebanking/model/Transaction.java
> +    @JoinColumn(name = "to_account", nullable = false)
same

2021-03-29 14:37 UTC, KseniiaMakarova commented on src/main/java/com/springboot/onlinebanking/service/AccountService.java
> +    Account findAccountByAccountNumber(String accountNumber);
```suggestion
    Account getByAccountNumber(String accountNumber);
```

2021-03-29 14:37 UTC, KseniiaMakarova commented on src/main/java/com/springboot/onlinebanking/service/TransactionService.java
> +    List<Transaction> getAllByAccount(int page, int size, Account account);
let's also have a `save()` method

2021-03-29 18:50 UTC, ShemsheyMaxim commented on src/main/java/com/springboot/onlinebanking/model/Currency.java
> +@Table(name = "cyrrencies")
done

2021-03-29 18:51 UTC, ShemsheyMaxim commented on src/main/java/com/springboot/onlinebanking/model/Transaction.java
> +    @OneToOne
done

2021-03-29 18:51 UTC, ShemsheyMaxim commented on src/main/java/com/springboot/onlinebanking/model/Transaction.java
> +    @JoinColumn(name = "to_account", nullable = false)
done

2021-03-29 18:51 UTC, ShemsheyMaxim commented on src/main/java/com/springboot/onlinebanking/service/AccountService.java
> +    Account findAccountByAccountNumber(String accountNumber);
done

2021-03-29 18:51 UTC, ShemsheyMaxim commented on src/main/java/com/springboot/onlinebanking/service/TransactionService.java
> +    List<Transaction> getAllByAccount(int page, int size, Account account);
done

2021-03-30 06:05 UTC, KseniiaMakarova approved these changes

2021-03-30 09:55 UTC, merged